### ISSUE TITLE
Build fails due to multiple Newtonsoft.Json assemblies

### ISSUE THREAD

**Issue by steverichey** [cawerkenthin/xAPIAndUnityProject#1]
I followed the tutorial provided in the readme, but I'm getting this error when pressing Play in Unity:

    Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/GBLXAPI/Scripts/JsonNet/Newtonsoft.Json.dll)

I removed the Newtonsoft assembly from the package cache, but of course Unity just restored it. The log said this when rebuilding:

    Assembly 'Packages/com.unity.collab-proxy/Lib/Editor/PlasticSCM/unityplastic.dll' will not be loaded due to errors: unityplastic references strong named Newtonsoft.Json Assembly references: 12.0.0.0 Found in project: 9.0.0.0. Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"

So I'm assuming that Unity Plastic is interfering with the version of Newtonsoft.Json otherwise used by this project. Unfortunately, I'm not aware of any way to remove this package (it doesn't show under "Built-in", "My assets", or "In project" under the package manager). I think the alternative would be to use the version of Newtonsoft.Json already included in Unity plastic, but it's not clear how to do that either.

Are there any known ways to resolve this issue? I'll continue to investigate on my end.

**Comment by cawerkenthin** [comment]
The project was developed in Unity 2019.4.28f1.  Apparently, later versions of Unity have added some form of Newtonsoft.  This may require a change in GBLxAPI.  You may wish to raise an issue at: https://github.com/gblxapi/UnityGBLxAPI

I have updated the instructions for this project to include use of 2019.4.28f1.

Thank you
